//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilityInspector
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime AvailableFrom { get; set; }
        public System.DateTime AvailableTill { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
