//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AvailabilityInspectors = new HashSet<AvailabilityInspector>();
            this.BetterReportInspectors = new HashSet<BetterReportInspector>();
            this.Cases = new HashSet<Case>();
            this.CertificateInspectors = new HashSet<CertificateInspector>();
            this.InspectorPlannings = new HashSet<InspectorPlanning>();
            this.Orders = new HashSet<Order>();
            this.Quotations = new HashSet<Quotation>();
            this.SickReportInspectors = new HashSet<SickReportInspector>();
        }
    
        public int Id { get; set; }
        public string Department { get; set; }
        public string Status { get; set; }
        public string Firstname { get; set; }
        public string Prefix { get; set; }
        public string Lastname { get; set; }
        public string Street { get; set; }
        public int HouseNumber { get; set; }
        public string HouseNumber_Addition { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<System.DateTime> ResetTokenEndTime { get; set; }
        public string Iban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailabilityInspector> AvailabilityInspectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetterReportInspector> BetterReportInspectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateInspector> CertificateInspectors { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual EmployeeStatu EmployeeStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InspectorPlanning> InspectorPlannings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SickReportInspector> SickReportInspectors { get; set; }
    }
}
