//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Festispec.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportElement
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public string ElementType { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int Order { get; set; }
        public string X_as { get; set; }
        public string Y_as { get; set; }
    
        public virtual ElementType ElementType1 { get; set; }
        public virtual Report Report { get; set; }
    }
}
